services:
  # 消息队列服务
  rabbitmq-service:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5


  # 串口服务
  serial-service:
    build:
      context: ./serial_service
      dockerfile: Dockerfile
    container_name: serial-service
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network


  # 一体机web服务
  ytjweb-service:
    build:
      context: ./ytj_web_service
      dockerfile: Dockerfile
    container_name: ytjweb-service
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network


  # 一体机mcp服务
  ytj-mcp-service:
    build:
      context: ./ytj_mcp_service
      dockerfile: Dockerfile
    container_name: ytj-mcp-service
    ports:
      - "8001:8001"
    depends_on:
      rabbitmq-service:
        condition: service_healthy
    networks:
      - app-network



  # chat-inspector服务 (精简版)
  chat-inspector-service:
    build:
      context: ./chat-inspector-prod
      dockerfile: Dockerfile
    container_name: chat-inspector-service
    ports:
      - "6274:6274"  # 客户端端口
      - "6277:6277"  # 服务器端口
    environment:
      CLIENT_PORT: 6274
      SERVER_PORT: 6277
      NODE_ENV: production
    # depends_on:
    #   ytj-mcp-service:
    #     condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped


networks:
  app-network:
    driver: bridge
